"""recording params

Revision ID: 64f321c7c569
Revises: c3327ba04b14
Create Date: 2026-08-11 09:26:01.592446

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f321c7c569'
down_revision: str | Sequence[str] | None = 'c3327ba04b14'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('edf_artifact_id', sa.Integer(), nullable=False),
    sa.Column('ictal_params_json', sa.JSON(), nullable=True),
    sa.Column('interictal_params_json', sa.JSON(), nullable=True),
    sa.Column('annotations_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edf_artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recording_params_edf_artifact_id'), 'recording_params', ['edf_artifact_id'], unique=True)
    op.create_index(op.f('ix_recording_params_id'), 'recording_params', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recording_params_id'), table_name='recording_params')
    op.drop_index(op.f('ix_recording_params_edf_artifact_id'), table_name='recording_params')
    op.drop_table('recording_params')
    # ### end Alembic commands ###
